# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/TaiLieu/multiply.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# IP: bd/TaiLieu/ip/multiply_mult_gen_0_0/multiply_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_mult_gen_0_0 || ORIG_REF_NAME==multiply_mult_gen_0_0} -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/project_1/project_1.gen/sources_1/bd/TaiLieu/multiply_ooc.xdc
