# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GiaPhuc/Project_1/Dense_0/project_1/project_1.srcs/sources_1/bd/TaiLieu/ip/multiply_mult_gen_0_0/multiply_mult_gen_0_0.xci
# IP: The module: 'multiply_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GiaPhuc/Project_1/Dense_0/project_1/project_1.gen/sources_1/bd/TaiLieu/ip/multiply_mult_gen_0_0/multiply_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GiaPhuc/Project_1/Dense_0/project_1/project_1.srcs/sources_1/bd/TaiLieu/ip/multiply_mult_gen_0_0/multiply_mult_gen_0_0.xci
# IP: The module: 'multiply_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GiaPhuc/Project_1/Dense_0/project_1/project_1.gen/sources_1/bd/TaiLieu/ip/multiply_mult_gen_0_0/multiply_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiply_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
