# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GiaPhuc/Project_1/Dense_0/project_1/project_1.srcs/sources_1/ip/rom_weight_fc64_2/rom_weight_fc64_2.xci
# IP: The module: 'rom_weight_fc64_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GiaPhuc/Project_1/Dense_0/project_1/project_1.gen/sources_1/ip/rom_weight_fc64_2/rom_weight_fc64_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_weight_fc64_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/GiaPhuc/Project_1/Dense_0/project_1/project_1.srcs/sources_1/ip/rom_weight_fc64_2/rom_weight_fc64_2.xci
# IP: The module: 'rom_weight_fc64_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GiaPhuc/Project_1/Dense_0/project_1/project_1.gen/sources_1/ip/rom_weight_fc64_2/rom_weight_fc64_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_weight_fc64_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
