# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Fully_connected/Fully_connected.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_connected || ORIG_REF_NAME==Fully_connected} -quiet] -quiet

# IP: bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/Fully_connected_Fully_Connected_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_connected_Fully_Connected_1_0_0 || ORIG_REF_NAME==Fully_connected_Fully_Connected_1_0_0} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/37e0/ram_data_fc64_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_data_fc64_3 || ORIG_REF_NAME==ram_data_fc64_3} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/5c37/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/7b18/multiply_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_mult_gen_0_0 || ORIG_REF_NAME==multiply_mult_gen_0_0} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/b0f5/rom_bias_fc64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_bias_fc64 || ORIG_REF_NAME==rom_bias_fc64} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/563a/rom_weight_fc64_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_weight_fc64_3 || ORIG_REF_NAME==rom_weight_fc64_3} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/96fb/rom_weight_fc64_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_weight_fc64_2 || ORIG_REF_NAME==rom_weight_fc64_2} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/97bb/rom_weight_fc64_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_weight_fc64_1 || ORIG_REF_NAME==rom_weight_fc64_1} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/577a/rom_weight_fc64_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_weight_fc64_0 || ORIG_REF_NAME==rom_weight_fc64_0} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/281c/ram_data_fc64_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_data_fc64_2 || ORIG_REF_NAME==ram_data_fc64_2} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/295c/ram_data_fc64_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_data_fc64_1 || ORIG_REF_NAME==ram_data_fc64_1} -quiet] -quiet

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/e99d/ram_data_fc64_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_data_fc64_0 || ORIG_REF_NAME==ram_data_fc64_0} -quiet] -quiet

# IP: bd/Fully_connected/ip/Fully_connected_zynq_ultra_ps_e_0_0/Fully_connected_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_connected_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Fully_connected_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Fully_connected/ip/Fully_connected_axi_bram_ctrl_0_0/Fully_connected_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_connected_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Fully_connected_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Fully_connected/ip/Fully_connected_blk_mem_gen_0_0/Fully_connected_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_connected_blk_mem_gen_0_0 || ORIG_REF_NAME==Fully_connected_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Fully_connected/ip/Fully_connected_axi_smc_0/Fully_connected_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_connected_axi_smc_0 || ORIG_REF_NAME==Fully_connected_axi_smc_0} -quiet] -quiet

# Block Designs: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/bd_4378.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_0/bd_4378_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_1/bd_4378_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_2/bd_4378_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_3/bd_4378_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_4/bd_4378_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_5/bd_4378_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_6/bd_4378_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_7/bd_4378_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_8/bd_4378_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_9/bd_4378_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_10/bd_4378_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_11/bd_4378_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_12/bd_4378_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_13/bd_4378_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_14/bd_4378_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_15/bd_4378_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_16/bd_4378_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_17/bd_4378_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_18/bd_4378_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_19/bd_4378_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_20/bd_4378_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_21/bd_4378_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_22/bd_4378_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_23/bd_4378_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_24/bd_4378_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_25/bd_4378_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_26/bd_4378_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_27/bd_4378_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_28/bd_4378_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_29/bd_4378_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_30/bd_4378_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_31/bd_4378_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_32/bd_4378_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_33/bd_4378_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_34/bd_4378_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_35/bd_4378_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_36/bd_4378_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_37/bd_4378_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_38/bd_4378_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/Fully_connected/ip/Fully_connected_rst_ps8_0_99M_0/Fully_connected_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Fully_connected_rst_ps8_0_99M_0 || ORIG_REF_NAME==Fully_connected_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/37e0/ram_data_fc64_3_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/5c37/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/5c37/ila_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/b0f5/rom_bias_fc64_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/563a/rom_weight_fc64_3_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/96fb/rom_weight_fc64_2_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/97bb/rom_weight_fc64_1_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/577a/rom_weight_fc64_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/281c/ram_data_fc64_2_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/295c/ram_data_fc64_1_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/e99d/ram_data_fc64_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/a2be/multiply_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_zynq_ultra_ps_e_0_0/Fully_connected_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_zynq_ultra_ps_e_0_0/Fully_connected_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Fully_connected_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Fully_connected_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_blk_mem_gen_0_0/Fully_connected_blk_mem_gen_0_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_1/bd_4378_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_1/bd_4378_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_2/bd_4378_arsw_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_3/bd_4378_rsw_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_4/bd_4378_awsw_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_5/bd_4378_wsw_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_6/bd_4378_bsw_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_10/bd_4378_s00a2s_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_11/bd_4378_sarn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_11/bd_4378_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_12/bd_4378_srn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_12/bd_4378_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_13/bd_4378_sawn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_13/bd_4378_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_14/bd_4378_swn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_14/bd_4378_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_15/bd_4378_sbn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_15/bd_4378_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_19/bd_4378_s01a2s_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_20/bd_4378_sarn_1_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_20/bd_4378_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_21/bd_4378_srn_1_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_21/bd_4378_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_22/bd_4378_sawn_1_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_22/bd_4378_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_23/bd_4378_swn_1_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_23/bd_4378_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_24/bd_4378_sbn_1_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_24/bd_4378_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_25/bd_4378_m00s2a_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_26/bd_4378_m00arn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_26/bd_4378_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_27/bd_4378_m00rn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_27/bd_4378_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_28/bd_4378_m00awn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_28/bd_4378_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_29/bd_4378_m00wn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_29/bd_4378_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_30/bd_4378_m00bn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_30/bd_4378_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_32/bd_4378_m01s2a_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_33/bd_4378_m01arn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_33/bd_4378_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_34/bd_4378_m01rn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_34/bd_4378_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_35/bd_4378_m01awn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_35/bd_4378_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_36/bd_4378_m01wn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_36/bd_4378_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_37/bd_4378_m01bn_0_ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_37/bd_4378_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/ooc.xdc

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Fully_connected_axi_smc_0 || ORIG_REF_NAME==Fully_connected_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_rst_ps8_0_99M_0/Fully_connected_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Fully_connected_rst_ps8_0_99M_0 || ORIG_REF_NAME==Fully_connected_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_rst_ps8_0_99M_0/Fully_connected_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Fully_connected_rst_ps8_0_99M_0 || ORIG_REF_NAME==Fully_connected_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/Fully_connected_ooc.xdc
