# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.runs/synth_1/Fully_connected_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param synth.incrementalSynthesisCache E:/TestVerilog/Test_DOAN1/project_1_IP_AXI/.Xil/Vivado-21156-DESKTOP-AF4K6S1/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.cache/wt [current_project]
set_property parent.project_path E:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property board_connections {som240_1_connector xilinx.com:kv260_carrier:som240_1_connector:1.3} [current_project]
set_property ip_repo_paths e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/ip_repo/Fully_Connected_1_1_0 [current_project]
update_ip_catalog
set_property ip_output_repo e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/ram_data_fc64_3.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/rom_bias_fc64.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/rom_weight_fc64_3.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/rom_weight_fc64_2.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/rom_weight_fc64_1.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/rom_weight_fc64_0.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/ram_data_fc64_2.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/ram_data_fc64_1.coe
add_files e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/ram_data_fc64_0.coe
read_verilog -library xil_defaultlib e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/hdl/Fully_connected_wrapper.v
add_files E:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.srcs/sources_1/bd/Fully_connected/Fully_connected.bd
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/37e0/ram_data_fc64_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/5c37/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/5c37/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/b0f5/rom_bias_fc64_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/563a/rom_weight_fc64_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/96fb/rom_weight_fc64_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/97bb/rom_weight_fc64_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/577a/rom_weight_fc64_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/281c/ram_data_fc64_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/295c/ram_data_fc64_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/e99d/ram_data_fc64_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_Fully_Connected_1_0_0/a2be/multiply_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_zynq_ultra_ps_e_0_0/Fully_connected_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_zynq_ultra_ps_e_0_0/Fully_connected_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_blk_mem_gen_0_0/Fully_connected_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_1/bd_4378_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_1/bd_4378_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_2/bd_4378_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_3/bd_4378_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_4/bd_4378_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_5/bd_4378_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_6/bd_4378_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_10/bd_4378_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_11/bd_4378_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_11/bd_4378_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_12/bd_4378_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_12/bd_4378_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_13/bd_4378_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_13/bd_4378_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_14/bd_4378_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_14/bd_4378_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_15/bd_4378_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_15/bd_4378_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_19/bd_4378_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_20/bd_4378_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_20/bd_4378_sarn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_21/bd_4378_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_21/bd_4378_srn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_22/bd_4378_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_22/bd_4378_sawn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_23/bd_4378_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_23/bd_4378_swn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_24/bd_4378_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_24/bd_4378_sbn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_25/bd_4378_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_26/bd_4378_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_26/bd_4378_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_27/bd_4378_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_27/bd_4378_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_28/bd_4378_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_28/bd_4378_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_29/bd_4378_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_29/bd_4378_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_30/bd_4378_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_30/bd_4378_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_32/bd_4378_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_33/bd_4378_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_33/bd_4378_m01arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_34/bd_4378_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_34/bd_4378_m01rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_35/bd_4378_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_35/bd_4378_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_36/bd_4378_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_36/bd_4378_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_37/bd_4378_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/bd_0/ip/ip_37/bd_4378_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_rst_ps8_0_99M_0/Fully_connected_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/ip/Fully_connected_rst_ps8_0_99M_0/Fully_connected_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all e:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.gen/sources_1/bd/Fully_connected/Fully_connected_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/TestVerilog/Test_DOAN1/project_1_IP_AXI/project_1_IP_AXI.srcs/utils_1/imports/synth_1/Fully_connected_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Fully_connected_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Fully_connected_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Fully_connected_wrapper_utilization_synth.rpt -pb Fully_connected_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
